### ISSUE TITLE
Remove support for billing-model (ROSA issue)

### ISSUE THREAD

**Issue by oharan2** [RedHatQE/openshift-cluster-management-python-wrapper#69]
In order to pass https://github.com/openshift/rosa/issues/1279 (ROSA cli issue), we created a [workaround](https://github.com/RedHatQE/openshift-cluster-management-python-wrapper/blob/main/ocm_python_wrapper/cluster.py#L423)

Once the problem is resolved, we need to remove our temporary solution.

Related PR:
https://github.com/RedHatQE/openshift-cluster-management-python-wrapper/pull/53

**Comment by oharan2** [comment]
@rnetser should be reopen? this issue is not resolved
(There's a TODO inside the code itself)

**Comment by rnetser** [comment]
it has been open for a long time and does not seem like rosa team will fix it soon; so the `TODO` in the code is enough for now
